# Generated by Django 3.2 on 2021-05-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
