# Generated by Django 3.2 on 2021-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=10),
        ),
    ]
