# Generated by Django 3.2 on 2021-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
