# Generated by Django 3.2 on 2021-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@getnada.com', max_length=254),
        ),
    ]
