# Generated by Django 3.2 on 2021-05-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
