# Generated by Django 3.2 on 2021-05-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@getnada.com', max_length=254),
        ),
    ]
