# Generated by Django 3.2 on 2021-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='1', max_length=13),
        ),
    ]
